module.exports = {
  mode: 'jit',
  purge: [
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './pages/**/*.{js,jsx,ts,tsx}',
    './public/index.html',
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './resources/**/*.vue',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      xs: '400px',
      sm: '640px',
      md: '768px',
      lg: '917px',
      xl: '1280px',
      '2xl': '1536px',
    },
    backgroundImage: (theme) => ({
      'sample-image': "url('./img/sample-image.jpg')",
    }),
    fontFamily: {
      base: ['Inter', 'sans-serif'],
    },
    // fontFamily: {
    //   base: ['Open Sans', 'sans-serif'],
    // },
    extend: {
      colors: {
        'peduly-primary': '#0288D1',
        'peduly-secondary': '#fcae03',
        'peduly-success': '#15cf74',
        'peduly-danger': '#eb0000',
        'peduly-dark': '#212121',
        'peduly-light': '#e4e4e4',
        'peduly-subtitle': '#717171',
        /* Fundraiser Color */
        'fundraiser-success': '#34A853',
        /* Merchant Color */
        'merchant-balance': '#0000000F',
        'merchant-subtitle': '#717171',
        /* bg modal */
        'black-transparent': 'rgba(0, 0, 0, .6)',
        'peduly-primary-smtransparent': 'rgba(231, 81, 59, 0.12)',
      },
      borderRadius: {
        small: '10px',
        base: '15px',
        button: '30px',
      },
      width: {
        'container-box': '484px',
        'box-width': '348px',
        'input-width': '324px',
        'nominal-box': '309px',
        'payment-logo': '57px',
        'payment-logo-square': '50px',
        'button-ganti': '60px',
        'toggle-button': '40px',
        'cek-button': '46px',
        'toggle-button2': '16px',
        'icon-dropdown': '12px',
        'input-kode': '180px',
        'data-fundraiser': '195px',
        'date-input': '157px',
        'card-table': '250px',
        'card-overflow': '840px',
        'card-overflow-large': '1200px',
        'default-img': '123px',
      },
      height: {
        'small-box': '60px',
        'button-ganti': '30px',
        'big-box': '122px',
        'text-area': '119px',
        'inputtext-area': '102px',
        'payment-logo': '43px',
        'payment-logo-square': '50px',
        'payment-logo-cc': '23px',
        'toggle-button': '20px',
        'cek-button': '24px',
        'toggle-button2': '16px',
        'metode-bayar': '72px',
        'metode-bayar-box': '52px',
        'data-fundraiser': '107px',
        'date-input': '38px',
        'card-table': '255px',
      },
      spacing: {
        'margin-left': '33px',
        'padding-bawah': '38px',
        'normal-space': '24px',
        'FundRaisertop-space': '21px',
        'arrow-space': '22px',
        'picture-height': '120px',
        'text-to-box': '19px',
        'nominal-atas': '14px',
        'textArea-atas': '17px',
        'nominal-kiri': '20px',
        'box-to-logo': '16px',
        'box-to-logo-up': '8px',
        'picture-to-text': '10px',
        'spacing-nominal-to-box': '12px',
        'spacing-nominal-to-box-big': '24px',
        'padding-textArea': '162px',
        'padding-instruksi': '43px',
        'padding-instruksi2': '37px',
        'FundRaiser-smallTable-Left': '26px',
        'FundRaiser-smallTable-Right': '47px',
        'Search-input': '51px',
        'Search-mx': '23px',
      },
      fontSize: {
        'super-small': '10px',
        small: '12px',
        basic: '14px',
        large: '16px',
        'semi-large': '18px',
        'super-large': '24px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
  ],
  variants: {
    extend: {},
  },
}
